kind: Pod
apiVersion: v1
metadata:
  name: curl-pod
spec:
  containers:
    - name: curl-pod
      image: gcr.io/salus-220516/curl-pod:latest
      command: ["/bin/bash"]
      args: ["-c", "while :; do echo '.'; sleep 5 ; done"]
  restartPolicy: OnFailure
